### ISSUE TITLE
淘宝的指纹支付不能用了

### ISSUE THREAD

**Issue by gthanmon** [eritpchy/Fingerprint-pay-magisk-taobao#4]
现在淘宝指纹支付不能自动输入了  请问可以修复吗

**Comment by eritpchy** [comment]
空了会修复的

**Comment by gthanmon** [comment]
好的 谢谢

**Comment by eritpchy** [comment]
fixed https://github.com/eritpchy/Fingerprint-pay-magisk-taobao/commit/41dc42e911b00e2607f76e396dc633af5d5012f6
